# NatLink macro definitions for NaturallySpeaking
# coding: latin-1
# Generated by vcl2py 2.8.5, Sat Feb 06 13:09:04 2016

import natlink
from natlinkutils import *
from VocolaUtils import *


class ThisGrammar(GrammarBase):

    gramSpec = """
        <dgndictation> imported;
        <1> = 'Mark as junk' ;
        <46> = 'Mark junk' ;
        <2> = ('work' | 'personal' ) 'inbox' ;
        <3> = ('Chris' | 'review' ) 'inbox' ;
        <4> = 'Flag That' ;
        <5> = 'Clear Flag' ;
        <folder> = 'Inbox' | 'Drafts' | 'Sent' | 'Calendar' | 'Contacts' | 'Tasks' ;
        <6> = 'switch To' <folder> ;
        <7> = 'find related' ('conversation' | 'sender' ) ;
        <8> = 'search' <dgndictation> ;
        <9> = 'New Message' ;
        <10> = 'New Message to Contact' ;
        <11> = 'Reply to' ('Message' | 'All' ) ;
        <12> = 'Forward Message' ;
        <13> = 'Get Mail' ;
        <14> = 'sort by' ('date' | 'sender' | 'flag' ) ;
        <15> = 'Final Message' ;
        <16> = 'Search Messages' ;
        <17> = 'Mark All Read' ;
        <18> = 'Kill Line' ;
        <19> = 'Save Attachment' ('one' | 'two' | 'three' | 'four' | 'five' | 'six' | 'seven' | 'eight' | 'nine' | 10) ;
        <20> = 'Save Attachment All' ;
        <21> = 'Kill Message' ;
        <22> = 'save to quick parts' ;
        <23> = 'Reply Here' ;
        <24> = 'Send That' ;
        <25> = 'Plain Text' ;
        <26> = 'Fix Return' ;
        <27> = 'Plain Text' ;
        <28> = ('To' | 'See See' | 'Be See See' ) 'That' ;
        <29> = 'Calendar' ;
        <30> = 'View' ('Month' | 'Work Week' ) ;
        <31> = 'Dismiss' ;
        <32> = 'Edit That' ;
        <33> = 'Print Preview' ;
        <34> = ('Design' | 'Edit' ) 'View' ;
        <35> = 'Edit Email Address' ;
        <36> = 'Update Email Address' ;
        <37> = 'Delete Email Address' ;
        <38> = 'Copy Email Address' ;
        <39> = 'New Contact' ;
        <40> = ('Use That' | 'Save and Close' ) ;
        <41> = 'Field' ('Categories' | 'File As' | 'Business' | 'Home' | 'Mobile' | 'Address' | 'Email' ) ;
        <42> = 'Home Address' ;
        <43> = 'Swap E-mail' ('two' | 'three') ;
        <44> = 'Use E-mail' ('two' | 'three') ;
        <45> = 'Close That' ;
        <47> = 'Close' ;
        <any> = <1>|<46>|<2>|<3>|<4>|<5>;
        <sequence> exported = <any>;
        <any_set2> = <any>|<6>|<7>|<8>|<9>|<10>|<11>|<12>|<13>|<14>|<15>|<16>|<17>|<18>|<19>|<20>;
        <sequence_set2> exported = <any_set2>;
        <any_set3> = <any>|<21>|<22>;
        <sequence_set3> exported = <any_set3>;
        <any_set4> = <any>|<23>|<24>;
        <sequence_set4> exported = <any_set4>;
        <any_set5> = <any>|<25>|<26>;
        <sequence_set5> exported = <any_set5>;
        <any_set6> = <any>|<27>;
        <sequence_set6> exported = <any_set6>;
        <any_set7> = <any>|<28>;
        <sequence_set7> exported = <any_set7>;
        <any_set8> = <any>|<29>;
        <sequence_set8> exported = <any_set8>;
        <any_set9> = <any>|<30>;
        <sequence_set9> exported = <any_set9>;
        <any_set10> = <any>|<31>;
        <sequence_set10> exported = <any_set10>;
        <any_set11> = <any>|<32>|<33>|<34>|<35>|<36>|<37>|<38>|<39>;
        <sequence_set11> exported = <any_set11>;
        <any_set12> = <any>|<40>|<41>|<42>|<43>|<44>;
        <sequence_set12> exported = <any_set12>;
        <any_set13> = <any>|<45>|<47>;
        <sequence_set13> exported = <any_set13>;
    """
    
    def initialize(self):
        self.load(self.gramSpec)
        self.currentModule = ("","",0)
        self.ruleSet1 = ['sequence']
        self.ruleSet2 = ['sequence_set2']
        self.ruleSet3 = ['sequence_set3']
        self.ruleSet4 = ['sequence_set4']
        self.ruleSet5 = ['sequence_set5']
        self.ruleSet6 = ['sequence_set6']
        self.ruleSet7 = ['sequence_set7']
        self.ruleSet8 = ['sequence_set8']
        self.ruleSet9 = ['sequence_set9']
        self.ruleSet10 = ['sequence_set10']
        self.ruleSet11 = ['sequence_set11']
        self.ruleSet12 = ['sequence_set12']
        self.ruleSet13 = ['sequence_set13']

    def gotBegin(self,moduleInfo):
        # Return if wrong application
        window = matchWindow(moduleInfo,'outlook','')
        if not window: return None
        self.firstWord = 0
        # Return if same window and title as before
        if moduleInfo == self.currentModule: return None
        self.currentModule = moduleInfo

        self.deactivateAll()
        title = string.lower(moduleInfo[1])
        if string.find(title,'') >= 0:
            for rule in self.ruleSet1:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'microsoft outlook') >= 0:
            for rule in self.ruleSet2:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'message') >= 0:
            for rule in self.ruleSet3:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'message (plain text)') >= 0:
            for rule in self.ruleSet4:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'message (html)') >= 0:
            for rule in self.ruleSet5:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'message (rich text)') >= 0:
            for rule in self.ruleSet6:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'select names') >= 0:
            for rule in self.ruleSet7:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'personal folders') >= 0:
            for rule in self.ruleSet8:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'calendar') >= 0:
            for rule in self.ruleSet9:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'overdue') >= 0:
            for rule in self.ruleSet10:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'contacts') >= 0:
            for rule in self.ruleSet11:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'- contact') >= 0:
            for rule in self.ruleSet12:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass
        if string.find(title,'print preview') >= 0:
            for rule in self.ruleSet13:
                try:
                    self.activate(rule,window)
                except natlink.BadWindow:
                    pass

    def convert_number_word(self, word):
        if   word == 'zero':
            return '0'
        elif word == 'one':
            return '1'
        elif word == 'two':
            return '2'
        elif word == 'three':
            return '3'
        elif word == 'four':
            return '4'
        elif word == 'five':
            return '5'
        elif word == 'six':
            return '6'
        elif word == 'seven':
            return '7'
        elif word == 'eight':
            return '8'
        elif word == 'nine':
            return '9'
        else:
            return word

    # 'Mark as junk'
    def gotResults_1(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{alt+h}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            top_buffer += 'j'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            top_buffer += 'b'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_1(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 10, '\'Mark as junk\'', e)
            self.firstWord = -1

    # 'Mark junk'
    def gotResults_46(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{alt+h}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            top_buffer += 'j'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            top_buffer += 'b'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_46(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 10, '\'Mark junk\'', e)
            self.firstWord = -1

    # ('work' | 'personal') 'inbox'
    def gotResults_2(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+y}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            limit = ''
            limit += '6'
            for i in range(to_long(limit)):
                top_buffer += '{Left}{left}{up}'
                top_buffer = do_flush(False, top_buffer);
                dragon2_arg1 = ''
                dragon2_arg1 += '100'
                saved_firstWord = self.firstWord
                call_Dragon('Wait', 'i', [dragon2_arg1])
                self.firstWord = saved_firstWord
            top_buffer += '{Down_'
            word = fullResults[0 + self.firstWord][0]
            if word == 'work':
                top_buffer += '1'
            elif word == 'personal':
                top_buffer += '5'
            top_buffer += '}'
            top_buffer += '{Right}{Down}{Right}{enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_2(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 13, '(\'work\' | \'personal\') \'inbox\'', e)
            self.firstWord = -1

    # ('Chris' | 'review') 'inbox'
    def gotResults_3(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+y}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '100'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            limit = ''
            limit += '6'
            for i in range(to_long(limit)):
                top_buffer += '{Left}{left}{up}'
                top_buffer = do_flush(False, top_buffer);
                dragon2_arg1 = ''
                dragon2_arg1 += '100'
                saved_firstWord = self.firstWord
                call_Dragon('Wait', 'i', [dragon2_arg1])
                self.firstWord = saved_firstWord
            top_buffer += '{Down_1}'
            top_buffer += '{Right}{Down}'
            top_buffer += 'M'
            top_buffer += '{Right}{down_'
            word = fullResults[0 + self.firstWord][0]
            if word == 'Chris':
                top_buffer += '1'
            elif word == 'review':
                top_buffer += '2'
            top_buffer += '}{enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_3(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 14, '(\'Chris\' | \'review\') \'inbox\'', e)
            self.firstWord = -1

    # 'Flag That'
    def gotResults_4(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+G}{Enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_4(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 16, '\'Flag That\'', e)
            self.firstWord = -1

    # 'Clear Flag'
    def gotResults_5(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+G}{Alt+e}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_5(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 17, '\'Clear Flag\'', e)
            self.firstWord = -1

    def get_folder(self, list_buffer, functional, word):
        list_buffer += word
        return list_buffer

    # 'switch To' <folder>
    def gotResults_6(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+y}{Left}'
            word = fullResults[1 + self.firstWord][0]
            top_buffer = self.get_folder(top_buffer, False, word)
            top_buffer += '{Enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('outlook.vcl', 31, '\'switch To\' <folder>', e)
            self.firstWord = -1

    # 'find related' ('conversation' | 'sender')
    def gotResults_7(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{shift+f10}'
            top_buffer += 'f'
            word = fullResults[1 + self.firstWord][0]
            if word == 'conversation':
                pass  # no actions
            elif word == 'sender':
                top_buffer += '{Down}'
            top_buffer += '{enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_7(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 32, '\'find related\' (\'conversation\' | \'sender\')', e)
            self.firstWord = -1

    # 'search' <_anything>
    def gotResults_8(self, words, fullResults):
        if self.firstWord<0:
            return
        fullResults = combineDictationWords(fullResults)
        opt = 1 + self.firstWord
        if opt >= len(fullResults) or fullResults[opt][1] != 'converted dgndictation':
            fullResults.insert(opt, ['', 'converted dgndictation'])
        try:
            top_buffer = ''
            top_buffer += '{ctrl+e}'
            word = fullResults[1 + self.firstWord][0]
            top_buffer += word
            top_buffer += '{enter}'
            top_buffer += '{Tab_3}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
        except Exception, e:
            handle_error('outlook.vcl', 33, '\'search\' <_anything>', e)
            self.firstWord = -1

    # 'New Message'
    def gotResults_9(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+n}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_9(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 34, '\'New Message\'', e)
            self.firstWord = -1

    # 'New Message to Contact'
    def gotResults_10(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+a}m'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_10(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 35, '\'New Message to Contact\'', e)
            self.firstWord = -1

    # 'Reply to' ('Message' | 'All')
    def gotResults_11(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            word = fullResults[1 + self.firstWord][0]
            if word == 'Message':
                top_buffer += '{Ctrl+r}'
            elif word == 'All':
                top_buffer += '{Ctrl+Shift+r}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_11(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 36, '\'Reply to\' (\'Message\' | \'All\')', e)
            self.firstWord = -1

    # 'Forward Message'
    def gotResults_12(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+f}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_12(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 37, '\'Forward Message\'', e)
            self.firstWord = -1

    # 'Get Mail'
    def gotResults_13(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+t}e{Enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_13(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 38, '\'Get Mail\'', e)
            self.firstWord = -1

    # 'sort by' ('date' | 'sender' | 'flag')
    def gotResults_14(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{alt+v}'
            top_buffer += 'ab'
            word = fullResults[1 + self.firstWord][0]
            if word == 'date':
                top_buffer += 'd'
            elif word == 'sender':
                top_buffer += 'f'
            elif word == 'flag':
                top_buffer += 'g'
            top_buffer += '{alt+h}{esc}{esc}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_14(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 39, '\'sort by\' (\'date\' | \'sender\' | \'flag\')', e)
            self.firstWord = -1

    # 'Final Message'
    def gotResults_15(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{End}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_15(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 42, '\'Final Message\'', e)
            self.firstWord = -1

    # 'Search Messages'
    def gotResults_16(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+Shift+f}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_16(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 43, '\'Search Messages\'', e)
            self.firstWord = -1

    # 'Mark All Read'
    def gotResults_17(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+e}e'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_17(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 44, '\'Mark All Read\'', e)
            self.firstWord = -1

    # 'Kill Line'
    def gotResults_18(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Del}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_18(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 45, '\'Kill Line\'', e)
            self.firstWord = -1

    # 'Save Attachment' 1..10
    def gotResults_19(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+f}n{Down_'
            word = fullResults[1 + self.firstWord][0]
            top_buffer += self.convert_number_word(word)
            top_buffer += '}{Up}{Enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_19(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 46, '\'Save Attachment\' 1..10', e)
            self.firstWord = -1

    # 'Save Attachment All'
    def gotResults_20(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+f}n{Up}{Enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_20(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 47, '\'Save Attachment All\'', e)
            self.firstWord = -1

    # 'Kill Message'
    def gotResults_21(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+F4}'
            top_buffer += 'n'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_21(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 50, '\'Kill Message\'', e)
            self.firstWord = -1

    # 'save to quick parts'
    def gotResults_22(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '200'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            top_buffer += 'n'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '200'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            top_buffer += 'q'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '200'
            saved_firstWord = self.firstWord
            call_Dragon('Wait', 'i', [dragon_arg1])
            self.firstWord = saved_firstWord
            top_buffer += 's'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_22(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 51, '\'save to quick parts\'', e)
            self.firstWord = -1

    # 'Reply Here'
    def gotResults_23(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Home}{Shift+End}{Del}{Enter_3}{Left_2}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_23(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 53, '\'Reply Here\'', e)
            self.firstWord = -1

    # 'Send That'
    def gotResults_24(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+f}e{Enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_24(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 54, '\'Send That\'', e)
            self.firstWord = -1

    # 'Plain Text'
    def gotResults_25(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+o}ty'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_25(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 56, '\'Plain Text\'', e)
            self.firstWord = -1

    # 'Fix Return'
    def gotResults_26(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{End}{Del}{Shift+Enter}{Right}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_26(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 57, '\'Fix Return\'', e)
            self.firstWord = -1

    # 'Plain Text'
    def gotResults_27(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+o}ty'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_27(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 59, '\'Plain Text\'', e)
            self.firstWord = -1

    # ('To' | 'See See' | 'Be See See') 'That'
    def gotResults_28(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+'
            word = fullResults[0 + self.firstWord][0]
            if word == 'To':
                top_buffer += 'o'
            elif word == 'See See':
                top_buffer += 'c'
            elif word == 'Be See See':
                top_buffer += 'b'
            top_buffer += '}{Down}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_28(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 61, '(\'To\' | \'See See\' | \'Be See See\') \'That\'', e)
            self.firstWord = -1

    # 'Calendar'
    def gotResults_29(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+v}gc'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_29(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 64, '\'Calendar\'', e)
            self.firstWord = -1

    # 'View' ('Month' | 'Work Week')
    def gotResults_30(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+'
            word = fullResults[1 + self.firstWord][0]
            if word == 'Month':
                top_buffer += 'm'
            elif word == 'Work Week':
                top_buffer += 'r'
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_30(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 66, '\'View\' (\'Month\' | \'Work Week\')', e)
            self.firstWord = -1

    # 'Dismiss'
    def gotResults_31(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+d}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_31(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 68, '\'Dismiss\'', e)
            self.firstWord = -1

    # 'Edit That'
    def gotResults_32(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Enter}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_32(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 71, '\'Edit That\'', e)
            self.firstWord = -1

    # 'Print Preview'
    def gotResults_33(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+f}v'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_33(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 72, '\'Print Preview\'', e)
            self.firstWord = -1

    # ('Design' | 'Edit') 'View'
    def gotResults_34(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+v}vc'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_34(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 73, '(\'Design\' | \'Edit\') \'View\'', e)
            self.firstWord = -1

    # 'Edit Email Address'
    def gotResults_35(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+o}{Tab_17}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_35(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 74, '\'Edit Email Address\'', e)
            self.firstWord = -1

    # 'Update Email Address'
    def gotResults_36(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+o}{Tab_17}{Ctrl+v}{Alt+s}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_36(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 75, '\'Update Email Address\'', e)
            self.firstWord = -1

    # 'Delete Email Address'
    def gotResults_37(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+o}{Tab_17}{Del}{Alt+s}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_37(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 76, '\'Delete Email Address\'', e)
            self.firstWord = -1

    # 'Copy Email Address'
    def gotResults_38(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+o}{Tab_17}{Ctrl+c}{Esc}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_38(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 77, '\'Copy Email Address\'', e)
            self.firstWord = -1

    # 'New Contact'
    def gotResults_39(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Ctrl+n}'
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += 'Category'
            dragon_arg2 = ''
            dragon_arg2 += 'Main'
            saved_firstWord = self.firstWord
            call_Dragon('HeardWord', 'ssssssss', [dragon_arg1, dragon_arg2])
            self.firstWord = saved_firstWord
            top_buffer += '{Tab_3}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_39(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 78, '\'New Contact\'', e)
            self.firstWord = -1

    # ('Use That' | 'Save and Close')
    def gotResults_40(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+s}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_40(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 81, '(\'Use That\' | \'Save and Close\')', e)
            self.firstWord = -1

    # 'Field' ('Categories' | 'File As' | 'Business' | 'Home' | 'Mobile' | 'Address' | 'Email')
    def gotResults_41(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '4'
            dragon_arg2 = ''
            eval_template2_arg1 = ''
            eval_template2_arg1 += '{"n":1, "e":2, "s":3, "w":4, "ne":5, "se":6, "sw":7, "nw":8}[%a]'
            eval_template2_arg2 = ''
            eval_template2_arg2 += 'sw'
            dragon_arg2 += eval_template(eval_template2_arg1, eval_template2_arg2)
            saved_firstWord = self.firstWord
            call_Dragon('SetMousePosition', 'iii', [dragon_arg1, dragon_arg2])
            self.firstWord = saved_firstWord
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += '2'
            dragon_arg2 = ''
            eval_template2_arg1 = ''
            eval_template2_arg1 += '15*%a'
            eval_template2_arg2 = ''
            eval_template2_arg2 += '5'
            dragon_arg2 += eval_template(eval_template2_arg1, eval_template2_arg2)
            dragon_arg3 = ''
            eval_template2_arg1 = ''
            eval_template2_arg1 += '15*%a'
            eval_template2_arg2 = ''
            eval_template2_arg2 += '-5'
            dragon_arg3 += eval_template(eval_template2_arg1, eval_template2_arg2)
            saved_firstWord = self.firstWord
            call_Dragon('SetMousePosition', 'iii', [dragon_arg1, dragon_arg2, dragon_arg3])
            self.firstWord = saved_firstWord
            top_buffer = do_flush(False, top_buffer);
            saved_firstWord = self.firstWord
            call_Dragon('ButtonClick', 'ii', [])
            self.firstWord = saved_firstWord
            top_buffer += '{Shift+Tab_'
            word = fullResults[1 + self.firstWord][0]
            if word == 'Categories':
                top_buffer += '24'
            elif word == 'File As':
                top_buffer += '18'
            elif word == 'Business':
                top_buffer += '16'
            elif word == 'Home':
                top_buffer += '14'
            elif word == 'Mobile':
                top_buffer += '10'
            elif word == 'Address':
                top_buffer += '8'
            elif word == 'Email':
                top_buffer += '4'
            top_buffer += '}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_41(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 85, '\'Field\' (\'Categories\' | \'File As\' | \'Business\' | \'Home\' | \'Mobile\' | \'Address\' | \'Email\')', e)
            self.firstWord = -1

    # 'Home Address'
    def gotResults_42(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer = do_flush(False, top_buffer);
            dragon_arg1 = ''
            dragon_arg1 += 'Field'
            dragon_arg2 = ''
            dragon_arg2 += 'Address'
            saved_firstWord = self.firstWord
            call_Dragon('HeardWord', 'ssssssss', [dragon_arg1, dragon_arg2])
            self.firstWord = saved_firstWord
            top_buffer += '{Tab} {Down_2}{Enter}{Tab} {Shift+Tab_2}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_42(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 87, '\'Home Address\'', e)
            self.firstWord = -1

    # 'Swap E-mail' 2..3
    def gotResults_43(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Shift+Tab} {Down '
            word = fullResults[1 + self.firstWord][0]
            top_buffer += self.convert_number_word(word)
            top_buffer += '}{Enter}{Tab}{Ctrl+c}'
            top_buffer += '{Shift+Tab} {Down}{Enter}{Tab}{Left}{Ctrl+v}{Backspace 2}'
            top_buffer += '{Shift+Right}{Ctrl+x}'
            top_buffer += '{Shift+Tab} {Down '
            word = fullResults[1 + self.firstWord][0]
            top_buffer += self.convert_number_word(word)
            top_buffer += '}{Enter}{Tab}{Ctrl+v}'
            top_buffer += '{Shift+Tab} {Down}{Enter}{Tab}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_43(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 92, '\'Swap E-mail\' 2..3', e)
            self.firstWord = -1

    # 'Use E-mail' 2..3
    def gotResults_44(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Shift+Tab} {Down '
            word = fullResults[1 + self.firstWord][0]
            top_buffer += self.convert_number_word(word)
            top_buffer += '}{Enter}{Tab}{Ctrl+x}'
            top_buffer += '{Shift+Tab} {Down}{Enter}{Tab}{Ctrl+v}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 2
            if len(words) > 2: self.gotResults_44(words[2:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 94, '\'Use E-mail\' 2..3', e)
            self.firstWord = -1

    # 'Close That'
    def gotResults_45(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+c}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_45(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 97, '\'Close That\'', e)
            self.firstWord = -1

    # 'Close'
    def gotResults_47(self, words, fullResults):
        if self.firstWord<0:
            return
        try:
            top_buffer = ''
            top_buffer += '{Alt+c}'
            top_buffer = do_flush(False, top_buffer);
            self.firstWord += 1
            if len(words) > 1: self.gotResults_47(words[1:], fullResults)
        except Exception, e:
            handle_error('outlook.vcl', 97, '\'Close\'', e)
            self.firstWord = -1

thisGrammar = ThisGrammar()
thisGrammar.initialize()

def unload():
    global thisGrammar
    if thisGrammar: thisGrammar.unload()
    thisGrammar = None
